package com.piloto.cdi.kernel.types;

public enum EventType {
    STATE_TRANSITION,
    TOOL_EXECUTION,
    TOOL_FAILURE,
    GOAL_CREATED,
    GOAL_UPDATED,
    GOAL_COMPLETED,
    GOAL_DEVIATION,
    MEMORY_WRITE,
    MEMORY_VALIDATION,
    EVALUATION_RESULT,
    POLICY_VIOLATION,
    SYSTEM_ERROR,
    TENANT_REGISTERED,
    TENANT_UNREGISTERED,
    HALLUCINATION_PREVENTED,
    DELIBERATION_APPROVED,
    DELIBERATION_REJECTED
}
